name: ProMining
version: '1.0'
main: com.promining.ProMining
api-version: '1.20'
depend: [Vault, PlaceholderAPI]
authors: [Luke0630]
description: プロ用マイニング（資材サバ専用）

commands:
  mining:
    permission: promining

permissions:
  promining:
    description: mining
    children:
      promining: true
    default: op
  promining.miningotherblock:
    description: the player that have this permission can break other blocks
    default: op
  promining.editVillager:
    default: op